destination:    ./_site
safe:           true
lsi:            false
include:        [".htaccess"]
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink: /:categories/:year/:title
markdown_ext:   markdown,mkd,mkdn,md
# permalink: /writing/:categories/:year/:title

markdown: redcarpet
pygments: true # default python pygments have been replaced by pygments.rb
